
DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, NOMBRE VARCHAR(50) NOT NULL, APELLIDO VARCHAR(50) NOT NULL, NUMERO_MATRICULA INT NOT NULL);




INSERT INTO ODONTOLOGOS(NOMBRE,APELLIDO,NUMERO_MATRICULA) VALUES ('Valeria','Gonzalez',4829);
INSERT INTO ODONTOLOGOS(NOMBRE,APELLIDO,NUMERO_MATRICULA) VALUES ('Juan','Gonzalez',2457);
